language: python

python:
  - "2.7"

# command to install dependencies
install:
  - pip install . --use-mirrors

# command to run tests
script: nosetests

notifications:
  flowdock:
    - secure: "kgOTXIpYHHiM+mdsbtiHb3EqfTQ4FCzdkAwEwvOLv3bWRyK4uphPMFkihYY5\nvGpoiEdP3Ql5eaTTeAoewSI+Z+fo1sYtyRfgcLEaKk4/L8Q98VECIeTx7NBY\nFExw251GyqecQBDTZ7GnmpP2AoV6t8BdL/qTiRshUSOC0lh1V/Y="
